home/urls.py
from django.conf.urls import include, url
from home import views


urlpatterns = [
	url(r'^$', views.HomeView.as_view(), name='home'),
	url(r'^academy/$', views.AcademyView.as_view(), name='academy'),
	url(r'^tune/$', views.TuneView.as_view(), name='tune'),
	url(r'^journal/$', views.JournalView.as_view(), name='journal'),
]

login/urls.py
from django.conf.urls import url
from login import views

urlpatterns = [
	url(r'^$', views.LoginFormView.as_view(), name='login'),
	url(r'^logout/$', views.user_logout, name='logout'),
	url(r'^username/$', views.check_username, name='username_validation'),
	url(r'^setup/$', views.UserSetupView.as_view(), name='setup'),
	url(r'^signup/$', views.signup, name='signup'),
]

pulsecode/urls.py
from django.conf.urls import include, url
from django.contrib import admin
from login.views import user_logout
from upload.views import JournalWriteView
from home.views import IndexView


urlpatterns = [
    url(r'^$', IndexView.as_view(), name='index'),
    url(r'^admin/', admin.site.urls),
	url(r'^login/', include('login.urls', namespace='login')),
	url(r'^upload/', include('upload.urls', namespace='upload')),
    url(r'^logout/', user_logout, name='logout'),
    url(r'^home/', include('home.urls', namespace='home')),
    url(r'^posting/', include('posting.urls', namespace='posting')),
    
    url(r'^journal/', include('journal.urls', namespace='journal')),
    url(r'^track/', include('track.urls', namespace='track')),
]

home/views.py
from django.shortcuts import render
from django.views.generic.base import TemplateView
from django.http import JsonResponse
from posting.models import Post, Member
from django.http import HttpResponseRedirect
from django.core.urlresolvers import reverse

# Create your views here.
class HomeView(TemplateView):
	template_name = 'home/home.html'

	def get_context_data(self):
		context = super(HomeView, self).get_context_data()
		if not self.request.user.is_authenticated():
			return context
		else:
			try:
				member = Member.objects.get(user=self.request.user)
				context['name'] = member.name
				context['picture'] = member.picture.url
				return context
			except Member.DoesNotExist:
				return context

	def get(self, request):
		if not request.user.is_authenticated():
			return HttpResponseRedirect(reverse('login:login'))
		else:
			if not Member.objects.filter(user=request.user):
				return HttpResponseRedirect(reverse('login:setup'))
			else:
				return super(HomeView, self).get(request)

	def post(self, request):
		isscroll = request.POST['isscroll']
		
		if isscroll:
			startfrom = int(request.POST['startfrom'])
			linetype = request.POST['type']
			entitynum = 8
			# load 4 more form database
			if linetype == 'new':
				objects = Post.objects
			elif linetype == 'liked':
				try:
					user = Member.objects.get(user=request.user)
					objects = user.liked_post
				except Member.DoesNotExist:
					objects = None
			elif linetype == 'scraped':
				try:
					user = Member.objects.get(user=request.user)
					objects = user.scraped_post
				except Member.DoesNotExist:
					objects = None

			# get 8 more from objects
			if objects:
				new8 = objects.all()[::-1][startfrom:startfrom+entitynum] # newest 8
			else:
				new8 = None
				
			# make json
			result = {
				'entitynum': len(new8),
				'loaded': True,
				'entity':[],
			}
			if new8:
				for idx, obj in enumerate(new8):
					objtype = 'track' if hasattr(obj, 'track') else 'journal'
					taglist = []
					liked_user = []
					scraped_user = []
					for tag in obj.tag.all()[:3]:
						taglist.append(tag.name)

					for liked in obj.liked_member.all():
						liked_user.append(liked.user)

					liked_on = request.user in liked_user

					for scraped in obj.scraped_member.all():
						scraped_user.append(scraped.user)

					scraped_on = request.user in scraped_user

					# common factors
					result['entity'].append({})

					result['entity'][idx] = {
						'objtype': objtype,
						'title': obj.title,
						'author': obj.author.name,
						'tag': taglist,
						'liked_num': len(liked_user),
						'liked_on': liked_on,
						'scraped_num': len(scraped_user),
						'scraped_on': scraped_on,
						'comment_num': len(obj.comment.all()),
						'bgimage_url': obj.track.image.url if objtype=='track' else obj.journal.bgimage.url,
						'pk': obj.pk,
					}
					# track specific
					if objtype is 'track':
						entity = result['entity'][idx]
						entity['track'] = {}
						entity = entity['track']
						track = obj.track

						entity['audio_url'] = track.audio_file.url
						entity['bgimage_url'] = track.image.url
						entity['description'] = track.description
						datetime = track.datetime
					#journal specific
					else :
						entity = result['entity'][idx]
						entity['journal'] = {}
						entity = entity['journal']
						journal = obj.journal


			else: # the new list is empty
				result['loaded'] = False

		else: # not a scroll request, other requests like sidebar
			pass


		return JsonResponse(result)
class IndexView(TemplateView):
	template_name  = 'home/index.html'

	def get(self, request):
		if request.user.is_authenticated():
			return HttpResponseRedirect(reverse('home:home'))
		else:
			return super(IndexView, self).get(request)


class AcademyView(TemplateView):
	template_name = 'home/academy.html'

class JournalView(TemplateView):
    template_name = 'home/journal.html'

class TuneView(TemplateView):
	template_name = 'home/tune.html'

class TutorialView(TemplateView):
    template_name = 'home/tutorial.html'

home/templates/home/index.html
{% extends "base.html" %}

{% block viewport %}
<meta name="viewport" content="width=device-width, initial-scale=1.0, minimum-scale=1, maximum-scale=1, user-scalable=0" />
{% endblock viewport %}

{% block title %}Welcome to Pulsecode{% endblock title %}
{% block style %}
{{ block.super }}
<style>
	.panel-signup {
		background-color: #333333;
		color: white;
		padding: 10px;
		padding-top: 0px;
		border: solid 1px #ffffff;
		margin-top: 20px;
	}
	.btn-default {
		border: solid 1px #ffffff;
	}
	.btn-default:hover {
		border: solid 1px #ffffff;
	}
	.signin {
		font-size: 12pt;
		font-family: sans-serif;
		margin: 5px;
		margin-left: 0px;
	}
</style>

{% endblock style %}


{% load static %}
{% block body %}
	<div class="container">
		<div id="textbox1" class="row">
			<div class="col-xs-12 col-sm-6 col-lg-6">
				<h2>포스텍의 미디/컴퓨터 음악 팬을 위한 동아리</h2>
				<ul>
					<li>내가 알고 있는 멋진 아티스트를 알리세요.</li>
					<li>컴퓨터 음악을 직접 만드는 방법을 배우고, 지식을 공유하세요.</li>
					<li>내가 작곡한 곡을 올리고 피드백을 받으세요.</li>
				</ul>
			</div>
			<div class="col-xs-12 col-sm-6 col-lg-6">
				<form method="post" role="form" id="signup_form" action="{% url 'login:signup' %}">
					<div class="panel panel-default panel-signup">
						<div class="penel-body">
							<h3>부담 없이 가입하세요</h3>
							<p>사이트 가입 후 활동은 자유롭습니다. 둘러보기도 환영합니다.</p>
							{% csrf_token %}
							<div class="form-group">
								<input class="form-control form-text" name="username" type="text" role="username" />
								<span class="glyphicon glyphicon-ok"></span>
								<span class="glyphicon glyphicon-remove"></span>
								<span role="message"></span>
							</div>
							<div class="form-group has-success">
								<input class="form-control form-text" name="password" type="password" role="password" />
								<span class="glyphicon glyphicon-ok"></span>
								<span class="glyphicon glyphicon-remove"></span>
								<span role="message"></span>
							</div>
							<div class="form-group">
								<input class="form-control form-text" type="password" role="passwordconfirm" />
								<span class="glyphicon glyphicon-ok"></span>
								<span class="glyphicon glyphicon-remove"></span>
								<span role="message"></span>
							</div>
							<label class="c-input c-checkbox">
								<input class="form-checkbox" name="official" type="checkbox" role="officialmember">정회원으로 가입합니다.</input>
							</label>
							<p>정회원은 동아리 명부에 이름이 올라가며, 정기 모임과 세미나에 참가할 수 있고 메일을 받습니다. 또한 카카오톡 톡방에 초대받게 됩니다.</p>
							<div class="form-group">
								<input class="form-control form-text" name="povisid" type="text" role="povisid"/>
							</div>
							<input class="btn btn-default" type="submit" />
							<span>If you are a member, </span><a class="signin" href="{% url 'login:login' %}">Sign in</a>
						</div>
					</div>
				</form>
			</div>
		</div>
		<div class="row">
			<div class="col-lg-3">
			</div>
		</div>
	</div>	
{% endblock body %}
{% block script %}
{{ block.super }}
	<script>
	var username_correct = false;
	var password_correct = false;
	var password_confirm = false;
	var povisid_correct = true;
	$(document).ready(function(){
		$.ajaxSetup({
			headers: {'X-CSRFToken': getCookie("csrftoken")}
		});
		$('input[role="username"]').watermark('Username (Used for login)');
		$('input[role="password"]').watermark('Password');
		$('input[role="passwordconfirm"]').watermark('Password Confirm');
		$('[role="povisid"]').watermark("Povis ID(for mail and contact)").hide();
		$('.glyphicon-ok').hide();
		$('.glyphicon-remove').hide();
		$('input[type="submit"]').hide();	

		//form validation - client
		//-------------------------------username
		$('input[role="username"]').on('focusin focusout', function(){
			$.ajax({
				type: 'POST',
				url: '{% url "login:username_validation" %}',
				data: {
					username: $(this).val(),
				},
				success: function(data){
					if(data.success){
						username_correct = true;
						$('input[role="username"]').parent().find('[role="message"]').text(data.message);
						$('input[role="username"]').parent().find('.glyphicon-remove').hide();
						$('input[role="username"]').parent().find('.glyphicon-ok').show();
					}
					else{
						username_correct = false;
						$('input[role="username"]').parent().find('[role="message"]').text(data.message);
						$('input[role="username"]').parent().find('.glyphicon-ok').hide();
						$('input[role="username"]').parent().find('.glyphicon-remove').show();
					}
					showSubmit();
				}
			});
		});
		//------------------------------password
		$('input[role="password"]').on('keyup focusin focusout', function(){
			var password_rule=  /^(?=.*[0-9])(?=.*[!@#$%^&*])[a-zA-Z0-9!@#$%^&*]{7,15}$/;
			if($('input[role="password"]').val().match(password_rule)){
				password_correct = true;
				$('input[role="password"]').parent().find('[role="message"]').text('Good Password');
				$('input[role="password"]').parent().find('.glyphicon-remove').hide();
				$('input[role="password"]').parent().find('.glyphicon-ok').show();
			}
			else{
				password_correct = false;
				$('input[role="password"]').parent().find('[role="message"]').text('Should be between 7 to 15 characters which contain at least one numeric digit and a special character');
				$('input[role="password"]').parent().find('.glyphicon-ok').hide();
				$('input[role="password"]').parent().find('.glyphicon-remove').show();
			}
			$('input[role="passwordconfirm"]').trigger('focusout');
			showSubmit();
		});
		$('input[role="passwordconfirm"]').on('focusin keyup focusout', function(){
			if($('input[role="password"]').val()==$(this).val()){
				password_confirm = true;
				$('input[role="passwordconfirm"]').parent().find('[role="message"]').text('Matched');
				$('input[role="passwordconfirm"]').parent().find('.glyphicon-remove').hide();
				$('input[role="passwordconfirm"]').parent().find('.glyphicon-ok').show();
			}
			else {
				password_confirm = false;
				$('input[role="passwordconfirm"]').parent().find('[role="message"]').text('Password does not match');
				$('input[role="passwordconfirm"]').parent().find('.glyphicon-ok').hide();
				$('input[role="passwordconfirm"]').parent().find('.glyphicon-remove').show();
			}
			showSubmit();
		});
		//----------------------------povisid
		$('input[role="officialmember"]').click(function(e){
			if($(this).is(':checked')){
				$('[role="povisid"]').slideDown();
				if($('input[role="povisid"]').val().length == 0){
					povisid_correct = false;
				}
			}
			else{
				$('[role="povisid"]').slideUp();
				povisid_correct = true;
			}
			showSubmit();
		});
		$('input[role="povisid"]').on('keyup', function(){
			if($(this).val().length > 0) povisid_correct = true;
			else povisid_correct = false;
			showSubmit();
		});

		function showSubmit(){
			if(username_correct && password_correct && password_confirm && povisid_correct){
				$('input[type="submit"]').show();	
			}
			else{
				$('input[type="submit"]').hide();	
			}
		}
		$(document).on('keydown', function(e){
			var keyCode = e.keyCode || e.which;
			if(keyCode == 13){
				e.preventDefault();
			}
		});
	});
	</script>
	<script src="{% static 'watermark3.1.4/jquery.watermark.min.js' %}"></script>
	<script src="{% static 'indexvisualizer.js' %}"></script>
{% endblock script %}