home/urls.py
from django.conf.urls import include, url
from home import views


urlpatterns = [
	url(r'^$', views.HomeView.as_view(), name='home'),
	url(r'^academy/$', views.AcademyView.as_view(), name='academy'),
	url(r'^tune/$', views.TuneView.as_view(), name='tune'),
	url(r'^journal/$', views.JournalView.as_view(), name='journal'),
]

login/urls.py
from django.conf.urls import url
from login import views

urlpatterns = [
	url(r'^$', views.LoginFormView.as_view(), name='login'),
	url(r'^logout/$', views.user_logout, name='logout'),
	url(r'^username/$', views.check_username, name='username_validation'),
	url(r'^setup/$', views.UserSetupView.as_view(), name='setup'),
	url(r'^signup/$', views.signup, name='signup'),
]

pulsecode/urls.py
from django.conf.urls import include, url
from django.contrib import admin
from login.views import user_logout
from upload.views import JournalWriteView
from home.views import IndexView


urlpatterns = [
    url(r'^$', IndexView.as_view(), name='index'),
    url(r'^admin/', admin.site.urls),
	url(r'^login/', include('login.urls', namespace='login')),
	url(r'^upload/', include('upload.urls', namespace='upload')),
    url(r'^logout/', user_logout, name='logout'),
    url(r'^home/', include('home.urls', namespace='home')),
    url(r'^posting/', include('posting.urls', namespace='posting')),
    
    url(r'^journal/', include('journal.urls', namespace='journal')),
    url(r'^track/', include('track.urls', namespace='track')),
]

upload/urls.py
from django.conf.urls import url
from upload import views

urlpatterns = [
	url(r'^track/$', views.TrackUploadFormView.as_view(), name='track'),
	url(r'^journal/$', views.JournalWriteView.as_view(), name='journal'),
	url(r'^tutorial/$', views.JournalWriteView.as_view(), name='tutorial'),
]

templates/base.html
<!DOCTYPE html>
<html lang="ko">
<head>
	<meta charset="utf-8">
{% block viewport %}
	<meta name="viewport" content="width=device-width, initial-scale=1, minimum-scale=1">
{% endblock viewport %}
	<title>{% block title %}Pulse Code{% endblock title %}</title>

{% load static %}
	<link href="{% static "bootstrap3.3.6/css/bootstrap.min.css" %}" rel="stylesheet">
	
	<!--[if It IE 9]>
		<script src="{% static "html5shiv/html5shiv.js" %}"></script>
		<script src="{% static "respond/respond.min.js" %}"></script>
	<![endif]-->
	<link href='https://fonts.googleapis.com/css?family=Quicksand' rel='stylesheet' type='text/css'>
	<style>
		body {
			padding: 0;
			background-color: #111111;
			font-family: 'Quicksand', sans-serif, 'Malgun Gothic';
			color: #dddddd;
		}
		.panel-heading{
			background-color: #333333;
			color: #ffffff;
		}
		.panel-body{
			background-color: #111111;
		}
		.panel{
			border: 1px solid #333333;
		}
		.btn-default{
			background-color: #333333;
			color: #ffffff;
			border: 0px;
		}
		.btn-default:hover{
			background-color: #666666;
			color: #ffffff;
			border: 0px;
		}
		.btn-default:focus {
			background-color: #373737;
			color: #ffffff;
		}
		.alert-warning{
			background-color: #992222;
			color: #ffaaaa;
			border-color: #dddddd;
		}
		.alert-success{
			border-color: #000000;
		}
		a.titlelogo {
			color: #004c99;
		}
		a:hover {
			text-decoration: none;
		}
		h4.titlelogo {
			color: #dddddd;
		}
		html, body {
		  width: auto !important;
		  overflow: visible auto;
		  height: 100%;
		  margin: 0;
		  padding: 0;
		}
		.top52 {
			margin-top:52px;
		}
		.fileUpload {
		    position: relative;
		    display: block;
		    overflow: hidden;
		    margin: auto;
		    margin-top: 10px;
		}
		.fileUpload input.upload {
		    position: absolute;
		    top: 0;
		    right: 0;
		    margin: 0;
		    padding: 0;
		    font-size: 20px;
		    cursor: pointer;
		    opacity: 0;
		    filter: alpha(opacity=0);
		}
		.panel-default .panel-heading {
			background-color: #333333;
			border: #333333;
			color: #ffffff;
		}
	</style>
	{% block style %}
	{% endblock style %}
</head>
<body>
	{% block body %}
	{% endblock body %}

	<script src="{% static "cookie.js" %}"></script>
	<script src="{% static "jquery2.2.0/jquery-2.2.0.min.js" %}"></script>
	<script src="{% static "bootstrap3.3.6/js/bootstrap.min.js" %}"></script>
	<script src="{% static "integer.js" %}"></script>
	<script src="{% static "smallplayer.js" %}"></script>
	{% block script %}
	{% endblock script %}
</body>

</html>

templates/base_navigator.html
{% extends "base.html" %}
{% block style %}
	<style>
	.content {
		background-color: #111111;
		width: 100%;
		max-width: 1400px;
		padding: 0;
		padding-bottom: 52px;
		height: 1800px;
	}
	.profilespan {
		width: 20px;
		height: 20px;
		margin-right: 5px;
	}
	[role="profilepic"]{
		border-radius: 50%;
		width: 20px;
		height: auto;
	}
	@media all and (min-width:768px){
		.content {
			margin-left: auto;
			margin-right: auto;
			border: solid 1px #333333;
		}
	}
	.navbar-right {
		margin-right: 10px;
	}
	</style>
{% endblock style %}

{% block body %}
	<header class="topbar">
		<nav class="navbar navbar-inverse navbar-fixed-top" role="navigation">
			<div class="navbar-header">
				<button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#menu">
					<span class="icon-bar"></span>
					<span class="icon-bar"></span>
					<span class="icon-bar"></span>
				</button>
				<a class="navbar-brand" href="{% url 'home:home' %}">Pulsecode</a></li>
			</div>
			<div class="collapse navbar-collapse" id="menu">
				<ul class="nav navbar-nav" id="common">
					<li><a href="{% url 'home:academy' %}">Academy</a></li>
					<li><a href="{% url 'home:tune' %}">Tune</a></li>
					<li><a href="{% url 'home:journal' %}">Journal</a></li>
				</ul>
				<ul class="nav navbar-nav navbar-right" id="user_specific">
					<li class="dropdown">
						<a class="dropdown-toggle btn btn-sm" data-toggle="dropdown"><span class="glyphicon glyphicon-circle-arrow-up"></span> Write<span class="caret"></span></a>
						<ul class="dropdown-menu">
							<li><a href="{% url 'upload:track' %}">Track</a></li>
							<li><a href="{% url 'upload:journal' %}">Journal</a></li>
							<li><a href="{% url 'upload:tutorial' %}">Tutorial</a></li>
						</ul>
					</li>
					<li class="dropdown">
						<a class="dropdown-toggle btn btn-sm" data-toggle="dropdown"><span class="profilespan"><img src="{{ picture }}" role="profilepic"/></span> {{ name }}</a>
						<ul class="dropdown-menu">
							<li><a href="#">Profile</a></li>
							<li><a href="{% url 'login:setup' %}">Config</a></li>
							<li><a href="{% url 'login:logout' %}">Logout</a></li>
						</ul>
					</li>
				</ul>
			</div>
		</nav>
	</header>
	{% block content %}
	{% endblock content %}
{% endblock body %}

{% block script %}
{{ block.super }}
<script>
	$(document).ready(function(){
		{% if not name %}
			$('header').remove();
		{% endif %}
	})

</script>
{% endblock script %}

templates/base_sidebar.html
{% extends "base_navigator.html" %}
{% block style %}
{{ block.super }}
	<style>
	.scrollbar {
		background-color: #232323;
		height: 1800px;
		width: 100%;
		border: solid 1px #2a2a2a;
		padding: 5px;
	}
	@media all and (min-width:768px){
		.scrollbar {
			position: relative;
		}
		.sidebar {
			position: relative;
			width: 400px;
			height: 1800px;
			left: 100%;
			top: -1800px;
			background-color: #dadada;
			padding: 20px;
		}
		.content {
			padding-right: 400px;
			overflow: hidden;
		}
	}
	</style>
{% endblock style %}

{% block content %}
<div class="content top52" id="content">
	<div class="scrollbar" id="scrollbar">
		{% block scrollbar %}
		{% endblock scrollbar %}
	</div>

	<div class="sidebar hidden-xs" id="sidebar">
		{% block sidebar %}
		{% endblock sidebar %}
	</div>
</div>
{% endblock content %}

{% block script %}
{{ block.super }}

{% endblock script %}

templates/common_audiofield.html
<link rel="stylesheet" type="text/css" href="{{ STATIC_URL }}audiofield/page-player/css/page-player.css" />
<style type="text/css">
  ul.playlist li a {
    color: #333333;
    display: block;
    font-family: "Lucida Grande","DejaVu Sans","Bitstream Vera Sans","Verdana,Arial,sans-serif";
    font-size: 12px;
    vertical-align: top;
  }
</style>
<!-- soundManager.useFlashBlock: related CSS -->
<link rel="stylesheet" type="text/css" href="{{ STATIC_URL }}audiofield/flashblock/flashblock.css" />
<script type="text/javascript" src="{{ STATIC_URL }}audiofield/script/soundmanager2.js"></script>

<script>
/* --------
  Config override: This demo uses shiny flash 9 stuff, overwriting Flash 8-based defaults
  Alternate PP_CONFIG object must be defined before soundManager.onready()/onload() fire.
  Alternately, edit the config in page-player.js to simply use the values below by default
-------- */

// demo only, but you can use these settings too..
soundManager.flashVersion = 9;
soundManager.preferFlash = true; // for visualization effects
soundManager.useHighPerformance = true; // keep flash on screen, boost performance
soundManager.wmode = 'transparent'; // transparent SWF, if possible
soundManager.useFastPolling = true; // increased JS callback frequency
soundManager.url = {{ STATIC_URL }}+'audiofield/swf/';
soundManager.debugFlash = false;
soundManager.debugMode = true;
// Added
//soundManager.useHTML5Audio = false;

// custom page player configuration

var PP_CONFIG = {
  autoStart: false,      // begin playing first sound when page loads
  playNext: false,        // stop after one sound, or play through list until end
  useThrottling: false,  // try to rate-limit potentially-expensive calls (eg. dragging position around)</span>
  usePeakData: true,     // [Flash 9 only] whether or not to show peak data (left/right channel values) - nor noticable on CPU
  useWaveformData: false,// [Flash 9 only] show raw waveform data - WARNING: LIKELY VERY CPU-HEAVY
  useEQData: false,      // [Flash 9 only] show EQ (frequency spectrum) data
  useFavIcon: false,     // try to apply peakData to address bar (Firefox + Opera) - performance note: appears to make Firefox 3 do some temporary, heavy disk access/swapping/garbage collection at first(?) - may be too heavy on CPU
  useMovieStar: true     // Flash 9.0r115+ only: Support for a subset of MPEG4 formats.
}
</script>

<script type="text/javascript" src="{{ STATIC_URL }}audiofield/page-player/script/page-player.js"></script>
<script type="text/javascript">

// demo only..
function setTheme(sTheme) {
  var o = document.getElementsByTagName('ul')[0];
  o.className = 'playlist'+(sTheme?' '+sTheme:'');
  return false;
}
</script>